### PR TITLE
Remove unused packages and code refactor

### PR DESCRIPTION
**Pull request by champ96k**
- Code refactor
- Remove unused packages
- upgrade the `webview_flutter package` to `3.0.4` version
- Add const in const widgets
- Added analysis_options rule

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [x] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by juicycleff** [comment]
@champ96k why the code refactor?

**Comment by juicycleff** [comment]
@champ96k to my knowledge webview_flutter does not support web

**Comment by champ96k** [comment]
> 

@juicycleff Thanks for the reply, currently we are using this package `flutter-unity-view-widget` and we have some web view version issues, so we need to update all packages to the latest version (3.0+ Version)

 Technically we don't use webview for `flutter web`

**Comment by champ96k** [comment]
> @champ96k why the code refactor?

as I see in this package some source codes are not updated to the latest version, so I thought it's good to update. 

Let me know whats your view is on this.

**Comment by Ahmadre** [comment]
regarding webview_flutter, why don't you just use overrides?

```yaml
dependency_overrides:
  ffi: ^2.0.1
```

see: https://dart.dev/tools/pub/dependencies#dependency-overrides

**Pull request closed without merging**
