### PR TITLE
Update examples to null safety

### PR DESCRIPTION
**Pull request by timbotimbo**
## Description

The example code can't simply be pasted into a modern flutter project. It will show errors, mainly due to null-safety changes.
Given that the plugin supports null-safety from version 4.2.0 (18 months ago), it's safe to update the example.

Besides some changes in the UnityWidget parameters, this example project is still compatible all the way back to plugin 4.2.0. 

The last commit is a small cleanup by following most suggestions of flutter_lints.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [X] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by juicycleff** [comment]
@timbotimbo can you rebase on my draft PR. Would love to have this merged in

**Review by nenenkosi — APPROVED** [review]

**Review by dawiddszewczyk — APPROVED** [review]

**Comment by dawiddszewczyk** [comment]
its ok but like @juicycleff  said rebase on his draft PR

**Comment by timbotimbo** [comment]
@juicycleff 
I created #737 based on the new branch. I've made it a separate request to allow people to still use this one while they use the plugin up to version 2022.2.0.

Null safety changes to `_unityWidgetController` are now mostly redundant, as those examples still need to be updated to the global controller.

**Comment by timbotimbo** [comment]
Reopening this for visibility, as the global_unity_controller isn't making much progress.

**Review by RoyalCoder88 — APPROVED** [review]

**Comment by timbotimbo** [comment]
Flutter will likely come with a new release next week, 3.10 (or maybe 3.12).
This will include Dart 3, and drop support for code that isn't null-safe.

Therefore I will merge this to keep the example working for people on the latest flutter version.

This might cause some small merge conflicts for #733 and #729. But i'd rather help to solve some small merge conflicts, than hastily merge a new feature that might not be stable yet.

**Pull request merged**
