### PR TITLE
Remove Android's white background color.

### PR DESCRIPTION
**Pull request by timbotimbo**
## Description

This removes the white background set in Kotlin, which allows us to experiment with a transparent UnityWidget.
iOS doesn't need any change as this already works.

This should not affect most users, because to see any change you need to both manually configure Unity and adjust the android theme.

See this example of a video widget playing behind Unity to get an idea of the possible results.  
(The video is started on a small delay to show the black flash, which is a flutter bug with AndroidView.)

https://user-images.githubusercontent.com/11444698/203645680-dcb7812d-e0c6-4373-89f3-79d72bf6bc68.mp4

See [https://github.com/juicycleff/flutter-unity-view-widget/issues/190#issuecomment-1296383215](https://github.com/juicycleff/flutter-unity-view-widget/issues/190#issuecomment-1296383215) for more details.

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by nenenkosi — APPROVED** [review]

**Comment by fiercepark** [comment]
@timbotimbo How did you get the transparent unity background color on android? I set the camera color to black with transparency 0 as well as "render over native ui" and this does not work for me, it still shows the black background.

**Comment by timbotimbo** [comment]
@fiercepark
Check step 4 of the original comment here https://github.com/juicycleff/flutter-unity-view-widget/issues/190#issuecomment-1296383215.

I needed to adjust the android styles.xml to allow transparency.

**Comment by jesseburstrom** [comment]
Put submitted file in Assets folder Unity, and add to Android.manifest:

***@***.***/UnityThemeSelector.Translucent"
int android/app/src/main/AndroidManifest.xml

Also in build/web/UnityLibraryindex.html change to other file , this is for
web but should work for Android as well some code i wrote to make it
possible
have exact size of unity embedding, also added like 75px in Flutter for
width anf height to subtract in index.html so avoid getting scrollbars.

Lastly for web the fix to communicate from flutter to unity is the mising :

.then((unityInstance) => {console.log(unityInstance); mainUnityInstance =
unityInstance});

at end to actually setup UnityInstance.

Enjoy!

Den sön 4 dec. 2022 kl 14:03 skrev timbotimbo ***@***.***>:

**Review by juicycleff — APPROVED** [review]

**Comment by hehe605715432** [comment]
hey!
it worked well with @timbotimbo instructed at first.
However, the project stops working after enable HDR.
It works on unity version 2021.3.29f1c1.

I would really appreciate any help :)

**Pull request merged**
